### ISSUE TITLE
Why do you have a sepearate ~/Code directory?

### ISSUE THREAD

**Issue by kshenoy** [patrickf3139/dotfiles#23]
Hello, I'm intrigued by using a bare-repo for my dotfiles and while trying to learn more about it online, I stumbled across your setup. I'm not sure I understand why you store your dotfiles in two places. Could you please elaborate on that?

**Comment by PatrickF1** [comment]
Sure, my latest commit explains this a little better. https://github.com/PatrickF1/dotfiles/commit/6f6703dbb6d17ea53d5af7f0c67b79a1d0d56652
