### ISSUE TITLE
Limited access to fzf.fish

### ISSUE THREAD

**Issue by roland-5** [patrickf3139/dotfiles#27]
Sorry for spam comment here, but all [fzf.fish](https://github.com/PatrickF1/fzf.fish) is limited to collaborators:
```
 An owner of this repository has limited the ability to comment to users that are collaborators on this repository. 
```

![ps_20240407171626](https://github.com/PatrickF1/dotfiles/assets/44477799/b9f6eba3-188a-4dc6-b4ac-22e11bcd9225)

Because of this there is no option to like something, make issue or pull request or make topic in discussion.

**Comment by PatrickF1** [comment]
Hi @roland-5, no worries.

Sorry I didn't make it easy to find out why. See the only open issue in fzf.fish.

Is there a particular issue you'd like to file or comment you want to make somewhere?

Btw, I appreciate all your emoji's and comments left on the repo over the years. Having your engagement and encouragement really made working on it worthwhile. :)

**Comment by roland-5** [comment]
Issues? Not at all. I wanted to give a heart to the new edition and I noticed that I couldn't do it and I started looking for why.
I read your post on wiki and I fully understand and respect it. Even if you decided that you wanted to stop developing fzf.fish, you would have every right to do so.
fzf.fish was a godsend to me when I found it and has been making my work more enjoyable for a long time.
I don't know how to write proper code using fish yet, so I can't help, but at this point I don't even know what could be added to the project - for me it has everything I need.
Rest like a king and all the best!

**Comment by PatrickF1** [comment]
Thanks for understanding and your encouraging words :)

**Comment by PatrickF1** [comment]
Thinking about this some more, would you like me to give you contributor access so that you can be one of the few people who can tell me if something breaks? Even though I'm not doing major updates, the dependencies, especially fd and fzf, can shift under us. And I appreciate the emojis you leave around.

**Comment by roland-5** [comment]
Gladly do. fd hasn't changed or added anything so far (looking from release version 9), but fzf has been releasing new versions quite often lately and changing things a bit.

**Comment by PatrickF1** [comment]
Cool thanks, adding you now!
